RoomConfig:
    partmentId: a3d3473047464fba9196e224659cc377
    floorId: 11
    dromNumber: 5-1118
    areaId: 1
    cookie: COOKIE 

MailConfig:
    from: FROM
    envTo: TO
    to: 
    secret: SECRET
    host: smtp.163.com
    port: 465
    nickname: 电费提醒助手
    subject: 电费提醒
    body: 电费即将用完，请及时充值
    ssl: true

WarningThreshold: 100
